In [2]:
import keras
import pandas as pd
import numpy as np
import pickle
import os

In [47]:
def sigmoid(x,deriv=False):
    """deriv 导数"""
    if(deriv == True):
        return x*(1-x) # sigmoid 导数结果
    return 1/(1+np.exp(-x))

In [48]:
X = np.array([[0,0,1],[0,1,1],[0,1,0],[1,1,1],[0,1,1]])
X.shape

(5, 3)

In [49]:
y = np.array([[0],[1],[1],[0],[1]])
y.shape

(5, 1)

In [58]:
np.random.seed(1)

In [59]:
W0 = 2*np.random.random((3,4))-1 # 3 连接X， 4 连接 神经元

In [60]:
W0

array([[-0.16595599,  0.44064899, -0.99977125, -0.39533485],
       [-0.70648822, -0.81532281, -0.62747958, -0.30887855],
       [-0.20646505,  0.07763347, -0.16161097,  0.370439  ]])

In [61]:
W1 =2* np.random.random((4,1))+1 #输出层  4 连接 上一层神经元；  1 为输出

In [74]:
# 正向传播，反向传播
for j in range(600000):
    L0 = X
    L1 = sigmoid(np.dot(L0,W0))
    L2 = sigmoid(np.dot(L1,W1))
    L2_err=y-L2
#     print(L2_err.shape)

    if(j%10000) ==0:
        print("error"+ str(np.mean(np.abs(L2_err))))
        
    L2_delta= L2_err * sigmoid(L2,deriv = True)
#     print(L2_delta.shape)
    L1_err = L2_delta.dot(W1.T)
    L1_delta = L1_err * sigmoid(L1,deriv = True)
    

    W1 += L1.T.dot(L2_delta)
    W0 += L0.T.dot(L1_delta)

error0.0013589814586868066
error0.001285666974523733
error0.0012228270468854288
error0.0011681969169940777
error0.0011201413034326146
error0.0010774462651129443
error0.0010391893627373651
error0.0010046555522205424
error0.0009732809282606777
error0.0009446140436369461
error0.0009182886669953348
error0.0008940041876869481
error0.0008715112553873923
error0.0008506010792724828
error0.0008310973340396093
error0.0008128499545257311
error0.0007957303196332482
error0.0007796274725598926
error0.0007644451238862915
error0.0007500992529672889
error0.0007365161714977782
error0.0007236309476351438
error0.000711386113985784
error0.0006997306009811245
error0.0006886188506331657
error0.0006780100757175039
error0.000667867637016077
error0.0006581585170251333
error0.0006488528729633265
error0.0006399236553452602
error0.0006313462810572575
error0.0006230983519695669
error0.0006151594117799928
error0.0006075107351024476
error0.00060013514386754
error0.0005930168469562853
error0.0005861412996711667
error0

In [75]:
W1

array([[-5.58447347],
       [ 1.57929072],
       [-4.97063168],
       [ 9.64601961]])

In [77]:
W0

array([[ 3.10056236, -1.12452423,  2.54266478, -5.55372517],
       [-2.96261564,  0.22832938, -2.7793654 ,  5.30057574],
       [ 1.28198847, -2.63850202,  1.29004904, -2.4652259 ]])

In [82]:
L1 =sigmoid( X.dot(W0))
L1

array([[0.78278807, 0.06670123, 0.78415549, 0.07833221],
       [0.15701244, 0.08240026, 0.18402436, 0.94455644],
       [0.04914364, 0.55683563, 0.05844947, 0.99503604],
       [0.80532826, 0.02834096, 0.74141737, 0.06189774],
       [0.15701244, 0.08240026, 0.18402436, 0.94455644]])

In [84]:
L2 =sigmoid( L1.dot(W1))
L2 #？？？

array([[6.05849685e-04],
       [9.99418777e-01],
       [9.99950455e-01],
       [5.30679472e-04],
       [9.99418777e-01]])